if (NOT DEFINED PDX_NAME)
    set(PDX_NAME "unknown")
endif()

function(report_path_size label path)
    if (NOT EXISTS "${path}")
        message(STATUS "[size] ${PDX_NAME}: ${label} not found")
        return()
    endif()

    if (IS_DIRECTORY "${path}")
        file(GLOB_RECURSE entries LIST_DIRECTORIES false "${path}/*")
        set(total_bytes 0)
        foreach(entry IN LISTS entries)
            if (EXISTS "${entry}" AND NOT IS_DIRECTORY "${entry}")
                file(SIZE "${entry}" entry_bytes)
                math(EXPR total_bytes "${total_bytes} + ${entry_bytes}")
            endif()
        endforeach()
        message(STATUS "[size] ${PDX_NAME}: ${label}=${total_bytes} bytes (directory)")
    else()
        file(SIZE "${path}" total_bytes)
        message(STATUS "[size] ${PDX_NAME}: ${label}=${total_bytes} bytes")
    endif()
endfunction()

if (DEFINED PDEX_FILE AND EXISTS "${PDEX_FILE}")
    report_path_size("pdex" "${PDEX_FILE}")
else()
    message(STATUS "[size] ${PDX_NAME}: pdex file not found")
endif()

if (DEFINED PDX_FILE)
    report_path_size("pdx" "${PDX_FILE}")
else()
    message(STATUS "[size] ${PDX_NAME}: pdx file not found")
endif()
